### PR TITLE
AETHER-110

### PR DESCRIPTION
**Pull request by bimargulies**
Add a log message to take notice of the decision to use a mirror.

### CODE REVIEW

**Comment by bentmann** [comment]
Thanks. Two minor comments though:
- Please respect the existing codestyle
- If not already done, please submit a signed copy of the Sonatype CLA, see the README.md for more details.

**Comment by bimargulies** [comment]
I see some irony in the requirement for a paper copy of the CLA in
addition to an emailed scan.

Do you want me to push the format repair?

On Sat, Jul 16, 2011 at 12:05 PM, bentmann
reply@reply.github.com
wrote:

**Comment by bentmann** [comment]
You don't need to update the pull request, I can easily reformat the patch myself after merging. The comment on the code style was more a general thing to keep in mind.

**Comment by bimargulies** [comment]
thanks. I thought that I was doing maven style, the eclipse workspace
I was using had (I thought) the right settings loaded. Apparently, I
goofed.

On Sat, Jul 16, 2011 at 1:39 PM, bentmann
reply@reply.github.com
wrote:

**Comment by bimargulies** [comment]
I've emailed the scanned agreement to community @ sonatype.

**Comment by bentmann** [comment]
Merged.

**Pull request closed without merging**
